# TF 2.4.0 with CUDA 11.0 + cuDNN 8.0 pre-installed
FROM tensorflow/tensorflow:2.10.0-gpu

# Avoid interactive tz prompts, speed up installs
ENV DEBIAN_FRONTEND=noninteractive PIP_NO_CACHE_DIR=1

# (Optional) system packages you need
# RUN apt-get update && apt-get install -y --no-install-recommends \
#     git build-essential && rm -rf /var/lib/apt/lists/*

# Copy your Python deps
WORKDIR /work/
COPY requirements.txt .

# Install Python deps
RUN python -m pip install --upgrade pip && \
    pip install -r requirements.txt